# Based on https://codeberg.org/Codeberg-CI/examples/src/branch/main/NodeJS/.woodpecker.yaml
# and https://codeberg.org/LibreKitten/LibreKitten-gui/src/branch/production/.woodpecker.yaml
# The original license:
# Copyright (C) YEAR by AUTHOR EMAIL

# Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted.

# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# https://cjerrington.codeberg.page/eleventy-base-blog-site/blog/codebergpagesbuild/
#
# This file would typically be .woodpecker.yml in the root of your repository.
#
#
# SECRETS
# https://woodpecker-ci.org/docs/usage/secrets
# CBTOKEN needs a codeberg access token as secret in woodpecker config
# CBMAIL with email address for git config
# SOURCEREPO must be replaced with the source repo
# DESTREPO must be replaced with the target codeberg pages repo
# CBUSERNAME must be replaced with the user/org
#
#
# We also assume a domains file in the source repo that gets copied to
# .domains in the target repo so codeberg pages works for custom domains
#

steps:
    - name: clone-pages
      when:
          - event: tag
            ref: refs/tags/**
          - event: manual
            ref: refs/tags/**
      image: alpine/git
      commands:
          - chmod -R a+w .
          - git clone -b pages https://codeberg.org/ampmod/pages.git amp-build
          - chmod -R a+w amp-build

    - name: clean-up
      when:
          - event: tag
            ref: refs/tags/**
          - event: manual
            ref: refs/tags/**
      image: alpine/git
      commands:
          - cd amp-build
          - git config --global --add safe.directory /woodpecker/src/codeberg.org/ampmod/ampmod/amp-build
          - git config --global user.email "no@thankyou.com"
          - git config --global user.name "CI Builder"
          - git remote set-url origin https://$CBTOKEN@codeberg.org/ampmod/pages.git
          - git rm -rf ./*

    - name: install
      when:
          - event: tag
            ref: refs/tags/**
          - event: manual
            ref: refs/tags/**
      image: node:alpine
      commands:
          - corepack enable
          - pnpm i --frozen-lockfile

    - name: build
      when:
          - event: tag
            ref: refs/tags/**
          - event: manual
            ref: refs/tags/**
      image: node:alpine
      commands:
          - corepack enable
          - NODE_ENV=production IS_CBP_BUILD=true ESBUILD_WORKERS=8 pnpm run build
          # - cp domains build/.domains

    - name: push
      when:
          - event: tag
            ref: refs/tags/**
          - event: manual
            ref: refs/tags/**
      image: alpine/git
      environment:
          CBTOKEN:
              from_secret: cbtoken
      commands:
          - git config --global --add safe.directory /woodpecker/src/codeberg.org/ampmod/ampmod/amp-build
          - git config --global user.email "no@thankyou.com"
          - git config --global user.name "CI Builder"
          - cp -a ./packages/gui/build/. ./amp-build
          - cd ./amp-build
          - git add --all
          - git commit -m "Woodpecker CI Build for tag $(git describe --tags)"
          - git push -u origin pages
