name: Sync to Codeberg

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CODEBERG_SSH_KEY }}
          known_hosts: 'placeholder'

      - name: Add Codeberg to Known Hosts
        run: ssh-keyscan codeberg.org >> ~/.ssh/known_hosts

      - name: Sync Changes
        run: |
          # 1. Add Codeberg Remote
          git remote add codeberg git@codeberg.org:ampmod/ampmod.git
          
          git push codeberg develop || echo "probably nothing to do"